<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kantboot</groupId>
        <artifactId>global</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>global-standalone</artifactId>
    <name>global-standalone</name>


    <dependencies>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>util-all</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>system-auth</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>user-all</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2-extension</artifactId>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-provider-redis-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>tool-ip</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>tool-area</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

</project>