<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kantboot</groupId>
        <artifactId>util</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>util-data-change</artifactId>
    <description>数据变化工具模块，提供数据变化记录功能</description>

    <dependencies>
        <!-- 引入 Hutool 工具包 -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>
        <!-- 引入 Spring Boot Web Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- 引入 Spring Boot AOP Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <!-- 引入 util-cache 模块 -->
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>util-cache</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- 引入 util-rest 模块 -->
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>util-rest</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>util-auth</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

</project>