<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kantboot</groupId>
        <artifactId>dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>functional</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>functional-icon</module>
        <module>functional-all</module>
        <module>functional-file</module>
        <module>functional-pay</module>
        <module>functional-translate</module>
        <module>functional-email</module>
        <module>functional-chat</module>
    </modules>

</project>