<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kantboot</groupId>
        <artifactId>test</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>test-starter</artifactId>
    <name>test-starter</name>

    <dependencies>
        <!-- pgsql -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>util-all</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>global</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>system-setting</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>system-language</artifactId>
            <version>${revision}</version>
        </dependency>


        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>


        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>user-all</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-all</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>engine-computer</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>engine-jvm</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>engine-database</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>util-resolver</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>


        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>fp-all</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-juhe</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-alicloud-market</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>tool-area</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>official-plugin-tool-area</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>tool-ip</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>official-plugin-tool-ip</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>global-standalone</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.github.ua-parser</groupId>
            <artifactId>uap-java</artifactId>
            <version>1.6.1</version>
        </dependency>


        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-github</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-google</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-discord</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>developer</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-wechat</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-wechat-miniprogram</artifactId>
            <version>${revision}</version>
        </dependency>

    </dependencies>



</project>