<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kantboot</groupId>
        <artifactId>functional</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>functional-all</artifactId>
    <name>functional-all</name>

    <dependencies>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-icon</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-file</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-pay</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-translate</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-email</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-chat</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

</project>