<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kantboot</groupId>
        <artifactId>starter-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>starter-standalone</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>official-plugin-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>util-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>system-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>user-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>functional-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>official-plugin-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>fp-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>tool-all</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>thirdparty-all</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>engine-all</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>developer</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>global-standalone</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.kantboot</groupId>
            <artifactId>in-project</artifactId>
            <version>${revision}</version>
        </dependency>

    </dependencies>

</project>