<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.kantboot</groupId>
        <artifactId>dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>starter-parent</artifactId>
    <name>starter-parent</name>
    <packaging>pom</packaging>
    <modules>
        <module>starter-standalone</module>
        <module>starter-standalone-minimize</module>
    </modules>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-admin</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-auth</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-base-control</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-cache</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-crypto</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-data-change</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-email</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-event</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-exception</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-file</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-http</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-i18n</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-init</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-jpa</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-location</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-log</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-qrcode</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-resolver</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-rest</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-scan</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-setting</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-timer</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>util-all</artifactId>
                <version>${revision}</version>
            </dependency>


            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>system-auth</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>system-dict</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>system-language</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>system-setting</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>system-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>user-account</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>user-balance</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>user-interrelation</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>user-location</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>user-online</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>user-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>functional-file</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>functional-chat</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>functional-email</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>functional-pay</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>functional-translate</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>functional-icon</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>functional-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>official-plugin-user-location</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>official-plugin-functional-translate</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>official-plugin-tool-ip</artifactId>
                <version>${revision}</version>
            </dependency>


            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>official-plugin-tool-area</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>official-plugin-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>fp-carousel</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>fp-comment</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>fp-community</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>fp-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>gateway-client</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>gateway-server</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>global-standalone</artifactId>
                <version>${revision}</version>
            </dependency>


            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>engine-computer</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>engine-database</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>engine-jvm</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>engine-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>developer</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>tool-area</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>tool-ip</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>tool-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-alicloud-market</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-baidu-translate</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-discord</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-github</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-google</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-juhe</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-wechat</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-wechat-miniprogram</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-wechat-pay</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>thirdparty-all</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>in-project</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>starter-standalone</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.kantboot</groupId>
                <artifactId>starter-standalone-minimize</artifactId>
                <version>${revision}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>


</project>
